spring:
   data:
      jdbc:
         repositories:
            enabled: true
   jpa:
      hibernate:
         ddl-auto: update
   datasource:
      url: localhost:3306/bms_sql?useSSL=false
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver